import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '../../src/components/Navbar'
import Main from '../../src/components/Main'
import About from '../../src/components/About'
import Skills from '../../src/components/Skills'
import Contact from '../../src/components/Contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Suvro Bose | Full-Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar/>
      <Main/>
      <About/>
      <Skills/>
      {/* <Projects/> */}
      <Contact/>
    </div>
  )
}
